name: Recipe Build PR

on:
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Compile and test Java
        run: mvn -B test

      - name: NPM install
        run: npm ci

      - name: Check Java formatting
        run: npx prettier --check src/main/java src/test/java

      - name: Check webapp formatting
        run: npm run format:check

      - name: Test webapp
        run: npm run test:no-watch

      - name: Build angular
        run: npm run build

      - name: Package and verify webapp
        run: mvn -B verify

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
