name: Release recipe

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - name: test frontend
        run: npm run test:headless
      - name: build frontend
        run: npm run build

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: build backend
        run: mvn clean test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: set next development version
        run: mvn -B versions:set -DnextSnapshot=true -DgenerateBackupPoms=false
      - run: echo "npm-next-version=$(npm version patch --no-git-tag-version)" >> $GITHUB_OUTPUT
        id: npm_next_version
      - run: npm version ${{ steps.npm_next_version.outputs.npm-next-version }}-SNAPSHOT --no-git-tag-version
      - run: |
          git config --global user.name 'version-bump'
          git config --global user.email 'noreply@ethy.ch'
          git commit -am "chore(release): ${{ steps.npm_next_version.outputs.npm-next-version }}-SNAPSHOT [skip ci]"
          git push
